// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-YGH2Xygo6JCwbhUFo2lyl6ime6higMA',
    appId: '1:634035102445:web:28f8a3f9409e1a5ba4e2e4',
    messagingSenderId: '634035102445',
    projectId: 'spend-wise-prem',
    authDomain: 'spend-wise-prem.firebaseapp.com',
    storageBucket: 'spend-wise-prem.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPNuoW4WDqrZTNADmQyWMiqO7-WEg_0JU',
    appId: '1:634035102445:android:af221c5f657f65eba4e2e4',
    messagingSenderId: '634035102445',
    projectId: 'spend-wise-prem',
    storageBucket: 'spend-wise-prem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb4Nks0TM_5kaUosvKjSmxhMfl73JThS4',
    appId: '1:634035102445:ios:adb7255b134ddc72a4e2e4',
    messagingSenderId: '634035102445',
    projectId: 'spend-wise-prem',
    storageBucket: 'spend-wise-prem.firebasestorage.app',
    iosBundleId: 'com.example.spendWise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb4Nks0TM_5kaUosvKjSmxhMfl73JThS4',
    appId: '1:634035102445:ios:adb7255b134ddc72a4e2e4',
    messagingSenderId: '634035102445',
    projectId: 'spend-wise-prem',
    storageBucket: 'spend-wise-prem.firebasestorage.app',
    iosBundleId: 'com.example.spendWise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-YGH2Xygo6JCwbhUFo2lyl6ime6higMA',
    appId: '1:634035102445:web:5b625d1a5543e0f4a4e2e4',
    messagingSenderId: '634035102445',
    projectId: 'spend-wise-prem',
    authDomain: 'spend-wise-prem.firebaseapp.com',
    storageBucket: 'spend-wise-prem.firebasestorage.app',
  );
}
